<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Evert',
                'last_name' => 'Rodríguez',
                'phone' => '77712345',
                'gender' => 'male',
                'address' => 'Santa Cruz',
                'email' => 'evert.rodriguez@gmail.com',
                'document_type' => 'CI',
                'document_number' => '1234567',
                'status' => true,
                'password' => Hash::make('nakroth'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'María',
                'last_name' => 'González',
                'phone' => '77798765',
                'gender' => 'female',
                'address' => 'Calle Libertad #456, Santa Cruz',
                'email' => 'maria.gonzalez@email.com',
                'document_type' => 'CI',
                'document_number' => '7654321',
                'status' => true,
                'password' => Hash::make('gerente123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'José',
                'last_name' => 'Pérez',
                'phone' => '77734567',
                'gender' => 'male',
                'address' => 'Radial 10 #789, Santa Cruz',
                'email' => 'jose.perez@email.com',
                'document_type' => 'CI',
                'document_number' => '2345678',
                'status' => true,
                'password' => Hash::make('venta123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ana',
                'last_name' => 'Morales',
                'phone' => '77756789',
                'gender' => 'female',
                'address' => 'Barrio Las Palmas #123, Santa Cruz',
                'email' => 'ana.morales@email.com',
                'document_type' => 'CI',
                'document_number' => '3456789',
                'status' => true,
                'password' => Hash::make('almacen123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luis',
                'last_name' => 'Vargas',
                'phone' => '77723456',
                'gender' => 'male',
                'address' => 'Plan 3000 #567, Santa Cruz',
                'email' => 'luis.vargas@email.com',
                'document_type' => 'CI',
                'document_number' => '4567890',
                'status' => true,
                'password' => Hash::make('caja123'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carmen',
                'last_name' => 'Silva',
                'phone' => '77787654',
                'gender' => 'female',
                'address' => 'Equipetrol #890, Santa Cruz',
                'email' => 'carmen.silva@email.com',
                'document_type' => 'CI',
                'document_number' => '5678901',
                'status' => true,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roberto',
                'last_name' => 'Mendoza',
                'phone' => '77745678',
                'gender' => 'male',
                'address' => 'Villa 1ro de Mayo #234, Santa Cruz',
                'email' => 'roberto.mendoza@email.com',
                'document_type' => 'CI',
                'document_number' => '6789012',
                'status' => true,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucía',
                'last_name' => 'Torres',
                'phone' => '77765432',
                'gender' => 'female',
                'address' => 'Av. Santos Dumont #456, Santa Cruz',
                'email' => 'lucia.torres@email.com',
                'document_type' => 'CI',
                'document_number' => '7890123',
                'status' => true,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernando',
                'last_name' => 'Chávez',
                'phone' => '77712398',
                'gender' => 'male',
                'address' => 'Barrio San José #789, Santa Cruz',
                'email' => 'fernando.chavez@email.com',
                'document_type' => 'CI',
                'document_number' => '8901234',
                'status' => true,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Patricia',
                'last_name' => 'Ramos',
                'phone' => '77789012',
                'gender' => 'female',
                'address' => 'Mutualista #123, Santa Cruz',
                'email' => 'patricia.ramos@email.com',
                'document_type' => 'CI',
                'document_number' => '9012345',
                'status' => true,
                'password' => Hash::make('password'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
