<div>
    <x-table.data-table
        :items="$users"
        header="livewire.user.components.header-user"
        table-header="livewire.user.components.table-header"
        table-rows="livewire.user.components.table-rows"
        modal="livewire.user.modal-edit-store"
        :editing="$editing"
        :relations="$allRoles"
        :search="$search"
        :show="$show"/>
</div>
