<div>
    <x-table.data-table
        header="livewire.permission.components.header-permission"
        :items="$permissions"
        table-header="livewire.permission.components.table-header"
        table-rows="livewire.permission.components.table-rows"
        modal="livewire.permission.modal-edit-store"
        :search="$search"
        :show="$show"
        :editing="$editing"
    />
</div>
