<div>
    <x-table.data-table
        :items="$roles"
        header="livewire.admin.security.role.components.header-rol"
        table-header="livewire.admin.security.role.components.table-header"
        table-rows="livewire.admin.security.role.components.table-rows"
        modal="livewire.admin.security.role.modal-edit-store"
        :editing="$editing"
        :relations="$all_permissions"
        :search="$search"
        :show="$show"/>
</div>
